CREATE TABLE "GAB_4663_PULSE_CHART"(
 "PRODUCT_LINE" VARCHAR(30),
 "PRODUCT_LINE_NAME" VARCHAR(50),
 "SALES_ACCOUNT" VARCHAR(50),
 "TARGET" DOUBLE,
 "PID" IDENTITY DEFAULT '0',
 "POST_DATE" DATE,
 UNIQUE ("PID"));